# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/slricks340/Desktop/ECEN 340 Seth Ricks Ian Fleming/ECEN-340/Final Lab/Final Project/Final Project.srcs/sources_1/ip/BITMAP_ROM/BITMAP_ROM.xci
# IP: The module: 'BITMAP_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/slricks340/Desktop/ECEN 340 Seth Ricks Ian Fleming/ECEN-340/Final Lab/Final Project/Final Project.gen/sources_1/ip/BITMAP_ROM/BITMAP_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BITMAP_ROM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/slricks340/Desktop/ECEN 340 Seth Ricks Ian Fleming/ECEN-340/Final Lab/Final Project/Final Project.srcs/sources_1/ip/BITMAP_ROM/BITMAP_ROM.xci
# IP: The module: 'BITMAP_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/slricks340/Desktop/ECEN 340 Seth Ricks Ian Fleming/ECEN-340/Final Lab/Final Project/Final Project.gen/sources_1/ip/BITMAP_ROM/BITMAP_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BITMAP_ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
